import React from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {Providers} from "@/app/providers";
import "./globals.css";
import {Toaster} from "react-hot-toast";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Toaster position={"top-right"}/>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
